os: linux
dist: bionic
addons:
  apt:
    packages:
      - libgtest-dev
      - cmake
      - make

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - ./ci/install_gtest.sh
  - mkdir build
  - cd build
install:
  - cmake ..
  - make -s
script: ctest -T test
