os: linux
dist: bionic
addons:
  apt:
    packages:
      - googletest

language: cpp
compiler:
  - gcc
  - clang

before_install:
  - mkdir build
install:
  - cd ./build
  - cmake ..
  - make
script: cd ./build && ctest -T test
