name: GitHub Actions

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    steps:
    - uses: actions/checkout@v2

    - name: APT Install GTest
      run: sudo apt-get install libgtest-dev

    - name: Install GTest
      run: $GITHUB_WORKSPACE/ci/install_gtest.sh

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -s

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V --no-compress-output -T test
